---
title: "Psychologieonderzoek<br>in Nederland, 2017--2021"
author: "VU Research Intelligence (<researchintelligence.ubvu@vu.nl>)"
institute: "UB VU"
date: "2023/05/08"
date-format: "D MMMM YYYY"
bibliography: references.bibtex
format:
  revealjs:
    theme: [simple,"../stylefiles/VU-revealjs.scss"]
    template-partials:
      - title-slide.html
    preview-links: auto
    callout-icon: false
---

## Agenda

### Vooraf:

Databronnen

OpenAlex *Concepts*

*Concept-weighted citation score*

Nota bene

### Dashboard 

## Databronnen
  
:::: {.columns}

::: {.column width="15%"}
:::

::: {.column width="70%"}
::: {.callout-note}
# Lokale CRIS
Publicatie data
:::

::: {.callout-note}
# OpenAlex ([link](https://openalex.org/){target="_blank" rel="noreferrer"})
  
Profiel, SSH thema's, citaties
:::

::: {.callout-note}
# Altmetric ([link](https://www.altmetric.com/){target="_blank" rel="noreferrer"})

Vermeldingen in geschreven media en beleidsdocumenten
:::
:::
::::

## OpenAlex labels: *Concepts*

- Gebaseerd op *Fields of Study* uit Microsoft Academic Graph.
- Geautomatiseerde semantische vergelijking tussen tekst uit artikel en relevante Wikipedia lemma's [[@shen2018](https://arxiv.org/pdf/1805.12216.pdf){target="_blank" rel="noreferrer"}].
- Meerdere *Fields of Study* mogelijk.
- Genest in hierarchie van Level 0 ('Psychologie') tot Level 5 ('Mental chronometry'). Level 0-1 gevalideerd, lager volledig automatisch.
- OpenAlex gebruikt eigen algoritme om FoS te voorspellen. [[OA docs](https://docs.openalex.org/api-entities/concepts){target="_blank" rel="noreferrer"}, [OA white paper](https://docs.google.com/document/d/1OgXSLriHO3Ekz0OYoaoP_h0sPcuvV4EqX7VgLLblKe4/edit){target="_blank" rel="noreferrer"}]

    
## Concept-weighted citations

- Naar analogie van *Field-weighted citations* van Elsevier
- Per concept-jaar groep wordt het gemiddelde aantal citaties berekend
- Normalisatie: gemiddelde = 1
- interpretatie: bijv CWC=1.8 -> 80% meer citaties dan verwacht.

## Nota bene

- Analyse alleen gedaan voor data die we kunnen terugvinden in OpenAlex/Altmetric.
  
  Alleen items met DOI, voornamelijk *peer-reviewed* artikelen

- Subtotalen (per uni/concept) tellen niet op tot totaal door overlap.


## Dashboard

:::: {.columns}

::: {.column width="49%"}
::: {.callout-note}
# Academisch profiel
Output

Gewogen citaties
:::

::: {.callout-note}
# Maatschappelijke relevantie
Output per SSH thema

Vermelding in media

Vermelding in beleid
:::
:::

::: {.column width="49%"}
::: {.callout-note}
# Samenwerkingen
Binnen consortium

Internationaal/nationaal
:::

::: {.callout-note}
# Internationale context
Benchmark
:::
:::

::::

## Dashboard {background-image="img/dashboard.png" background-size="70%" background-repeat="no-repeat" background-position="center"}

## Referenties
---
nocite: |
  @*
---

::: {#refs}
:::